header:
  frame_id: "camera_frame"
heighasdasdasdt: 480
width: 640
distortion_model: "plumb_bob"
d: [0.1, 0.05, 0.0, 0.0, 0.0]
k: [620.1, 0.0, 320.5, 0.0, 621.2, 240.5, 0.0, 0.0, 1.0]
r: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
p: [620.1, 0.0, 320.5, 0.0, 0.0, 621.2, 240.5, 0.0, .00, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi:
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
